// import { Geist, Geist_Mono, Lato } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// // Use the font variables in your CSS

// const lato = Lato({
//   subsets: ['latin'],
//   display: 'swap',
//   weight: ['400', '700','800'], // Optional: Specify the font weights you want to use
//   variable: '--font-lato',
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} ${lato.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }


import { Lato } from "next/font/google";
import "./globals.css";

// Define the Lato font variable
const lato = Lato({
  subsets: ['latin'],
  display: 'swap',
  weight: ['400', '700', '900'], // Optional: Specify the font weights you want
  variable: '--font-lato',
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${lato.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}

